version: "3.9"
services:
  postgres:
    image: postgres
    container_name: notiffly_postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  notiffly-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notiffly_api
    ports:
      - "5177:5177"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5177
      - Postgres:Host=postgres
      - Postgres:Port=5432
      - Postgres:Database=postgres
      - Postgres:User=postgres
      - Postgres:Password=pass123
    depends_on:
      - postgres

volumes:
  pgdata:
