apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: microservices.local
      http:
        paths:
          - path: /notifications(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: notifications-api
                port:
                  number: 5179
                  
          - path: /subscriptions(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: subscriptions-api
                port:
                  number: 5177