version: '3.9'
services:
  notifications-postgres:
    image: postgres
    container_name: notifications_postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: notifications_db
    volumes:
      - notifications_pgdata:/var/lib/postgresql/data

  notifications-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifications_api
    ports:
      - '5179:5179'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5179
      - Postgres:Host=notifications-postgres
      - Postgres:Port=5432
      - Postgres:Database=notifications_db
      - Postgres:User=postgres
      - Postgres:Password=pass123
    depends_on:
      - notifications-postgres

volumes:
  notifications_pgdata:
